### ISSUE TITLE
Honor SENZING_ENGINE_CONFIGURATION_JSON when building G2Module.ini

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-init-container#111] opened 2021-03-23 20:00 UTC
In `def change_module_ini(config):` function, `SENZING_ENGINE_CONFIGURATION_JSON`, if present, should be used to build contents of G2Module.ini.

**Comment by docktermj** [comment] 2021-03-23 20:14
An approach:

if `SENZING_ENGINE_CONFIGURATION_JSON` is defined, then transform it into TOML (INI) format and write to G2Module.ini.  If it doesn't exist, use the existing code.

**Comment by docktermj** [comment] 2021-03-23 20:20
Perhaps it's code like this:

```python
config = configparser.ConfigParser()
for key, value in config.get('SENZING_ENGINE_CONFIGURATION_JSON'):
    config[key] = value
```
Reference: https://docs.python.org/3/library/configparser.html#quick-start

**Comment by jeffadair** [comment] 2021-03-24 19:29
@docktermj it appears that this already happening. (Dupe of #86?)

I added this to my docker-compose yaml for the init containter



> SENZING_ENGINE_CONFIGURATION_JSON: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "BACKEND": "HYBRID",
            "CONNECTION": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres}:${POSTGRES_PORT:-5432}:${POSTGRES_DB:-G2}"
          },
          "C1": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres-res}:${POSTGRES_PORT:-5432}:${POSTGRES_DB:-G2}"
          },
          "C2": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres-libfeat}:${POSTGRES_PORT:-5432}:${POSTGRES_DB:-G2}"
          },
          "HYBRID": {
            "RES_FEAT": "C1",
            "RES_FEAT_EKEY": "C1",
            "RES_FEAT_LKEY": "C1",
            "RES_FEAT_STAT": "C1",
            "LIB_FEAT": "C2",
            "LIB_FEAT_HKEY": "C2"
          }
        }

And this is what ended up in the G2Module.ini

>[PIPELINE]
SUPPORTPATH = /opt/senzing/data
CONFIGPATH = /etc/opt/senzing
RESOURCEPATH = /opt/senzing/g2/resources
>
>[SQL]
CONNECTION = postgresql://postgres:postgres@senzing-postgres:5432:G2
BACKEND = HYBRID
>
> [HYBRID]
RES_FEAT = C1
RES_FEAT_EKEY = C1
RES_FEAT_LKEY = C1
RES_FEAT_STAT = C1
LIB_FEAT = C2
LIB_FEAT_HKEY = C2
>
> [C1]
CLUSTER_SIZE = 1
DB_1 = postgresql://postgres:postgres@senzing-postgres-res:5432:G2
>
> [C2]
CLUSTER_SIZE = 1
DB_1 = postgresql://postgres:postgres@senzing-postgres-libfeat:5432:G2

Where did you see this not working?

**Comment by jeffadair** [comment] 2021-03-24 19:41
I spoke with @docktermj and he clarified. Sometimes customers may specify values in the JSON that we don't currently support. Those need to make it to the final G2Module.ini. So we should just take the json as is and do a direct translation of the json to the ini file. SENZING_ENGINE_CONFIGURATION_JSON is meant for advanced use cases so let's not be too smart for our own good here.

**Closed** 2021-06-03 15:35 UTC
